# Generated by Django 4.0.2 on 2022-02-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questeion_text',
            new_name='question_text',
        ),
    ]
